"""add backtest_run and backtest_trade tables

Revision ID: 2e4f15e9600d
Revises: d389fb3ad723
Create Date: 2026-09-11 07:17:31.949999

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e4f15e9600d"
down_revision: str | Sequence[str] | None = "d389fb3ad723"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.String(length=10), nullable=False),
        sa.Column("end_date", sa.String(length=10), nullable=False),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("win_rate_pct", sa.Float(), nullable=False),
        sa.Column("average_return_pct", sa.Float(), nullable=False),
        sa.Column("total_pnl", sa.Float(), nullable=False),
        sa.Column("max_drawdown_pct", sa.Float(), nullable=False),
        sa.Column("run_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backtest_run_run_at"), "backtest_run", ["run_at"], unique=False
    )
    op.create_index(
        op.f("ix_backtest_run_strategy_name"),
        "backtest_run",
        ["strategy_name"],
        unique=False,
    )
    op.create_table(
        "backtest_trade",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backtest_run_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("entry_date", sa.DateTime(), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("exit_date", sa.DateTime(), nullable=False),
        sa.Column("exit_price", sa.Float(), nullable=False),
        sa.Column("exit_reason", sa.String(length=30), nullable=False),
        sa.Column("pnl", sa.Float(), nullable=False),
        sa.Column("return_pct", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["backtest_run_id"],
            ["backtest_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_backtest_trade_backtest_run_id"),
        "backtest_trade",
        ["backtest_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backtest_trade_symbol"), "backtest_trade", ["symbol"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_backtest_trade_symbol"), table_name="backtest_trade")
    op.drop_index(
        op.f("ix_backtest_trade_backtest_run_id"), table_name="backtest_trade"
    )
    op.drop_table("backtest_trade")
    op.drop_index(op.f("ix_backtest_run_strategy_name"), table_name="backtest_run")
    op.drop_index(op.f("ix_backtest_run_run_at"), table_name="backtest_run")
    op.drop_table("backtest_run")
    # ### end Alembic commands ###
