"""add fund_nav table

Revision ID: 4c2487b78ed3
Revises: a42961e384bf
Create Date: 2026-09-11 07:44:15.421674

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c2487b78ed3"
down_revision: str | Sequence[str] | None = "a42961e384bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fund_nav",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scheme_code", sa.String(length=20), nullable=False),
        sa.Column("scheme_name", sa.String(length=255), nullable=False),
        sa.Column("fund_house", sa.String(length=255), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("nav", sa.Float(), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("expense_ratio", sa.Float(), nullable=True),
        sa.Column("aum", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scheme_code",
            "date",
            "provider",
            name="uq_fund_nav_scheme_code_date_provider",
        ),
    )
    op.create_index(op.f("ix_fund_nav_date"), "fund_nav", ["date"], unique=False)
    op.create_index(
        op.f("ix_fund_nav_scheme_code"), "fund_nav", ["scheme_code"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fund_nav_scheme_code"), table_name="fund_nav")
    op.drop_index(op.f("ix_fund_nav_date"), table_name="fund_nav")
    op.drop_table("fund_nav")
    # ### end Alembic commands ###
