"""add portfolio and journal tables

Revision ID: a42961e384bf
Revises: 2e4f15e9600d
Create Date: 2026-09-11 07:35:37.986751

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a42961e384bf"
down_revision: str | Sequence[str] | None = "2e4f15e9600d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "holding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("average_cost", sa.Float(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_holding_symbol"), "holding", ["symbol"], unique=False)
    op.create_table(
        "journal_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("entry_date", sa.DateTime(), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("exit_date", sa.DateTime(), nullable=True),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("lessons_learned", sa.Text(), nullable=True),
        sa.Column("screenshot_path", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_journal_entry_created_at"),
        "journal_entry",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_journal_entry_symbol"), "journal_entry", ["symbol"], unique=False
    )
    op.create_table(
        "portfolio_transaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("asset_type", sa.String(length=20), nullable=False),
        sa.Column("transaction_type", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("realized_pnl", sa.Float(), nullable=True),
        sa.Column("transacted_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolio_transaction_symbol"),
        "portfolio_transaction",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_transaction_transacted_at"),
        "portfolio_transaction",
        ["transacted_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_portfolio_transaction_transacted_at"),
        table_name="portfolio_transaction",
    )
    op.drop_index(
        op.f("ix_portfolio_transaction_symbol"), table_name="portfolio_transaction"
    )
    op.drop_table("portfolio_transaction")
    op.drop_index(op.f("ix_journal_entry_symbol"), table_name="journal_entry")
    op.drop_index(op.f("ix_journal_entry_created_at"), table_name="journal_entry")
    op.drop_table("journal_entry")
    op.drop_index(op.f("ix_holding_symbol"), table_name="holding")
    op.drop_table("holding")
    # ### end Alembic commands ###
