"""add explanation table

Revision ID: d389fb3ad723
Revises: afdbdb5c00cf
Create Date: 2026-09-11 07:11:05.719863

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d389fb3ad723"
down_revision: str | Sequence[str] | None = "afdbdb5c00cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "explanation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_explanation_generated_at"),
        "explanation",
        ["generated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_explanation_symbol"), "explanation", ["symbol"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_explanation_symbol"), table_name="explanation")
    op.drop_index(op.f("ix_explanation_generated_at"), table_name="explanation")
    op.drop_table("explanation")
    # ### end Alembic commands ###
